- platform: broadlink      ### RoomName = Rumpus
  host: 192.168.255.255    ## IP Address of the Broadlink
  mac: "78:0f:77:00:xx:xx" ## MAC Address of the Broadlink
  timeout: 15
  type: rm_mini            ## Broadlink type
  switches:
    'Power CD':
      friendly_name: "amplifier Power CD"
      command_on: 'JgBEAAABKJQSEhI3EhISEhISEjcSEhI3EjcSEhI3EjcSNxISEjcSEhISEhISNxI3EjcSEhISEhISNxI3EhISEhISEjcSNxI3EgANBQ=='
      command_off: ''

    'Power Tuner':
      friendly_name: "amplifier Power Tuner"
      command_on: 'JgBEAAABKJQSEhISEjcSEhISEjcSEhI3EjcSNxISEjcSNxISEjcSEhISEhISNxI3EjcSEhISEhISNxI3EhISEhISEjcSNxI3EgANBQ=='
      command_off: ''

    'Power Tape':
      friendly_name: "amplifier Power Tape"
      command_on: 'JgBEAAABKJQSNxISEhISEhISEjcSEhI3EhISNxI3EjcSNxISEjcSEhISEhISNxI3EjcSEhISEhISNxI3EhISEhISEjcSNxI3EgANBQ=='
      command_off: ''

    'Tape Select':
      friendly_name: "amplifier Tape Select"
      command_on: 'JgBEAAABKJQSNxISEhISEhISEjcSEhI3EhISNxI3EjcSNxISEjcSEhISEhISNxI3EhISEhI3EhISNxI3EhISEhI3EjcSEhI3EgANBQ=='
      command_off: ''

    'Tape Back':
      friendly_name: "amplifier Tape Back"
      command_on: 'JgBEAAABKJQSNxISEhISEhISEjcSEhI3EhISNxI3EjcSNxISEjcSEhI3EjcSEhI3EjcSEhI3EhISEhISEjcSEhISEjcSEhI3EgANBQ=='
      command_off: ''

    'Tape Stop':
      friendly_name: "amplifier Tape Stop"
      command_on: 'JgBEAAABKJQSNxISEhISEhISEjcSEhI3EhISNxI3EjcSNxISEjcSEhISEhISNxI3EjcSEhI3EhISNxI3EhISEhISEjcSEhI3EgANBQ=='
      command_off: ''

    'Tape Play':
      friendly_name: "amplifier Tape Play"
      command_on: 'JgBEAAABKJQSNxISEhISEhISEjcSEhI3EhISNxI3EjcSNxISEjcSEhI3EhISNxI3EjcSEhI3EhISEhI3EhISEhISEjcSEhI3EgANBQ=='
      command_off: ''

    'Tape Rewind':
      friendly_name: "amplifier Tape Rewind"
      command_on: 'JgBEAAABKJQSNxISEhISEhISEjcSEhI3EhISNxI3EjcSNxISEjcSEhI3EjcSNxISEjcSEhI3EhISEhISEhISNxISEjcSEhI3EgANBQ=='
      command_off: ''

    'Tape Forward':
      friendly_name: "amplifier Tape Forward"
      command_on: 'JgBEAAABKJQSNxISEhISEhISEjcSEhI3EhISNxI3EjcSNxISEjcSEhISEjcSNxISEjcSEhI3EhISNxISEhISNxISEjcSEhI3EgANBQ=='
      command_off: ''

    'CD Previous':
      friendly_name: "amplifier CD Previous"
      command_on: 'JgBEAAABKJQSEhI3EhISEhISEjcSEhI3EjcSEhI3EjcSNxISEjcSEhI3EhISEhISEjcSEhISEhISEhI3EjcSNxISEjcSNxI3EgANBQ=='
      command_off: ''

    'CD Next':
      friendly_name: "amplifier CD Next"
      command_on: 'JgBEAAABKJQSEhI3EhISEhISEjcSEhI3EjcSEhI3EjcSNxISEjcSEhISEhISEhISEjcSEhISEhISNxI3EjcSNxISEjcSNxI3EgANBQ=='
      command_off: ''

    'CD Stop':
      friendly_name: "amplifier CD Stop"
      command_on: 'JgBEAAABKJQSEhI3EhISEhISEjcSEhI3EjcSEhI3EjcSNxISEjcSEhISEjcSNxISEjcSEhISEhISNxISEhISNxISEjcSNxI3EgANBQ=='
      command_off: ''

    'CD Play':
      friendly_name: "amplifier CD Play"
      command_on: 'JgBEAAABKJQSEhI3EhISEhISEjcSEhI3EjcSEhI3EjcSNxISEjcSEhI3EjcSNxISEjcSEhISEhISEhISEhISNxISEjcSNxI3EgANBQ=='
      command_off: ''

    'Disc Select':
      friendly_name: "amplifier Disc Select"
      command_on: 'JgBEAAABKJQSEhI3EhISEhISEjcSEhI3EjcSEhI3EjcSNxISEjcSEhI3EhISNxI3EjcSEhISEhISEhI3EhISEhISEjcSNxI3EgANBQ=='
      command_off: ''

    'Station -':
      friendly_name: "amplifier Station -"
      command_on: 'JgBEAAABKJQSEhISEjcSEhISEjcSEhI3EjcSNxISEjcSNxISEjcSEhI3EhISEhISEjcSEhISEhISEhI3EjcSNxISEjcSNxI3EgANBQ=='
      command_off: ''

    'Station +':
      friendly_name: "amplifier Station +"
      command_on: 'JgBEAAABKJQSEhISEjcSEhISEjcSEhI3EjcSNxISEjcSNxISEjcSEhISEhISEhISEjcSEhISEhISNxI3EjcSNxISEjcSNxI3EgANBQ=='
      command_off: ''

    'Selector CD':
      friendly_name: "amplifier Selector CD"
      command_on: 'JgBEAAABKJQSNxISEjcSEhISEjcSEhI3EhISNxISEjcSNxISEjcSEhISEhISNxI3EhISEhI3EhISNxI3EhISEhI3EjcSEhI3EgANBQ=='
      command_off: ''

    'Selector Tuner':
      friendly_name: "amplifier Selector Tuner"
      command_on: 'JgBEAAABKJQSNxISEjcSEhISEjcSEhI3EhISNxISEjcSNxISEjcSEhI3EjcSNxISEhISEhI3EhISEhISEhISNxI3EjcSEhI3EgANBQ=='
      command_off: ''

    'Selector Phono':
      friendly_name: "amplifier Selector Phono"
      command_on: 'JgBEAAABKJQSNxISEjcSEhISEjcSEhI3EhISNxISEjcSNxISEjcSEhI3EhISNxI3EhISEhI3EhISEhI3EhISEhI3EjcSEhI3EgANBQ=='
      command_off: ''

    'Volume +':
      friendly_name: "amplifier Volume +"
      command_on: 'JgBEAAABKJQSNxISEjcSEhISEjcSEhI3EhISNxISEjcSNxISEjcSEhISEjcSEhI3EhISEhISEhISNxISEjcSEhI3EjcSNxI3EgANBQ=='
      command_off: ''

    'Selector Tape 1':
      friendly_name: "amplifier Selector Tape 1"
      command_on: 'JgBEAAABKJQSNxISEjcSEhISEjcSEhI3EhISNxISEjcSNxISEjcSEhISEjcSNxI3EhISEhI3EhISNxISEhISEhI3EjcSEhI3EgANBQ=='
      command_off: ''

    'Selector Tape 2':
      friendly_name: "amplifier Selector Tape 2"
      command_on: 'JgBEAAABKJQSNxISEjcSEhISEjcSEhI3EhISNxISEjcSNxISEjcSEhI3EhISNxI3EjcSEhISEhISEhI3EhISEhISEjcSNxI3EgANBQ=='
      command_off: ''

    'Selector Line':
      friendly_name: "amplifier Selector Line"
      command_on: 'JgBEAAABKJQSNxISEjcSEhISEjcSEhI3EhISNxISEjcSNxISEjcSEhI3EjcSNxI3EhISEhI3EhISEhISEhISEhI3EjcSEhI3EgANBQ=='
      command_off: ''

    'Volume -':
      friendly_name: "amplifier Volume -"
      command_on: 'JgBEAAABKJQSNxISEjcSEhISEjcSEhI3EhISNxISEjcSNxISEjcSEhI3EjcSEhI3EhISEhISEhISEhISEjcSEhI3EjcSNxI3EgANBQ=='
      command_off: ''

