- platform: broadlink      ### RoomName = Rumpus
  host: 192.168.255.255    ## IP Address of the Broadlink
  mac: "78:0f:77:00:xx:xx" ## MAC Address of the Broadlink
  timeout: 15
  type: rm_mini            ## Broadlink type
  switches:
    'Power CD':
      friendly_name: "Pioneer Power CD"
      command_on: 'JgDMAAABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUOxQ7FAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUOxQ7FAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUOxQ7FAANBQ=='
      command_off: ''

    'Power Tuner':
      friendly_name: "Pioneer Power Tuner"
      command_on: 'JgDMAAABBoMUOxQUFBQUFBQUFDsUFBQ7FDsUOxQUFDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FDsUOxQUFDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FDsUOxQUFDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAANBQ=='
      command_off: ''

    'Power Tape':
      friendly_name: "Pioneer Power Tape"
      command_on: 'JgDMAAABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUOxQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUOxQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUOxQ7FAANBQ=='
      command_off: ''

    'Tape Select':
      friendly_name: "Pioneer Tape Select"
      command_on: 'JgDMAAABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUOxQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUOxQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUOxQ7FAANBQ=='
      command_off: ''

    'Back':
      friendly_name: "Pioneer Back"
      command_on: 'JgDMAAABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQ7FDsUFBQ7FDsUFBQ7FBQUOxQ7FBQUOxQUFDsUFBQUFAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQ7FDsUFBQ7FDsUFBQ7FBQUOxQ7FBQUOxQUFDsUFBQUFAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQ7FDsUFBQ7FDsUFBQ7FBQUOxQ7FBQUOxQUFDsUFBQUFAANBQ=='
      command_off: ''

    'Stop':
      friendly_name: "Pioneer Stop"
      command_on: 'JgDMAAABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQ7FBQUFBQ7FBQUOxQUFDsUOxQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQ7FBQUFBQ7FBQUOxQUFDsUOxQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUOxQ7FDsUFBQ7FBQUFBQ7FBQUOxQUFDsUOxQ7FAANBQ=='
      command_off: ''

    'Play':
      friendly_name: "Pioneer Play"
      command_on: 'JgDMAAABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQ7FBQUOxQ7FDsUFBQ7FBQUFBQ7FBQUOxQUFDsUFBQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQ7FBQUOxQ7FDsUFBQ7FBQUFBQ7FBQUOxQUFDsUFBQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQ7FBQUOxQ7FDsUFBQ7FBQUFBQ7FBQUOxQUFDsUFBQ7FAANBQ=='
      command_off: ''

    'Tape Rewind':
      friendly_name: "Pioneer Tape Rewind"
      command_on: 'JgDMAAABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQ7FBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUFBQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQ7FBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUFBQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQ7FBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUFBQ7FAANBQ=='
      command_off: ''

    'Tape Forward':
      friendly_name: "Pioneer Tape Forward"
      command_on: 'JgDMAAABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAADMwABBoMUOxQUFBQUFBQUFDsUFBQ7FBQUOxQ7FDsUOxQUFDsUFBQUFBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAANBQ=='
      command_off: ''

    'Chapter Back':
      friendly_name: "Pioneer Chapter Back"
      command_on: 'JgDMAAABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQ7FBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUFBQ7FAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQ7FBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUFBQ7FAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQ7FBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUFBQ7FAANBQ=='
      command_off: ''

    'Chapter Next':
      friendly_name: "Pioneer Chapter Next"
      command_on: 'JgDMAAABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQUFBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQUFBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQUFBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAANBQ=='
      command_off: ''

    'CD Stop':
      friendly_name: "Pioneer CD Stop"
      command_on: 'JgDMAAABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQUFDsUOxQUFDsUFBQUFBQUFBQUFDsUOxQ7FDsUOxQUFAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQUFDsUOxQUFDsUFBQUFBQUFBQUFDsUOxQ7FDsUOxQUFAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQUFDsUOxQUFDsUFBQUFBQUFBQUFDsUOxQ7FDsUOxQUFAANBQ=='
      command_off: ''

    'CD Play':
      friendly_name: "Pioneer CD Play"
      command_on: 'JgDMAAABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQ7FDsUOxQUFDsUFBQUFBQUFBQUFDsUOxQ7FDsUFBQUFAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQ7FDsUOxQUFDsUFBQUFBQUFBQUFDsUOxQ7FDsUFBQUFAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQ7FDsUOxQUFDsUFBQUFBQUFBQUFDsUOxQ7FDsUFBQUFAANBQ=='
      command_off: ''

    'Disc Select':
      friendly_name: "Pioneer Disc Select"
      command_on: 'JgDMAAABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQ7FBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUFBQ7FAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQ7FBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUFBQ7FAADMwABBoMUFBQ7FBQUFBQUFDsUFBQ7FDsUFBQ7FDsUOxQUFDsUFBQ7FBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUFBQ7FAANBQ=='
      command_off: ''

    'Station -':
      friendly_name: "Pioneer Station -"
      command_on: 'JgDMAAABBoMUFBQUFDsUFBQUFDsUFBQ7FDsUOxQUFDsUOxQUFDsUFBQ7FBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUFBQ7FAADMwABBoMUFBQUFDsUFBQUFDsUFBQ7FDsUOxQUFDsUOxQUFDsUFBQ7FBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUFBQ7FAADMwABBoMUFBQUFDsUFBQUFDsUFBQ7FDsUOxQUFDsUOxQUFDsUFBQ7FBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUFBQ7FAANBQ=='
      command_off: ''

    'Station +':
      friendly_name: "Pioneer Station +"
      command_on: 'JgDMAAABBoMUFBQUFDsUFBQUFDsUFBQ7FDsUOxQUFDsUOxQUFDsUFBQUFBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAADMwABBoMUFBQUFDsUFBQUFDsUFBQ7FDsUOxQUFDsUOxQUFDsUFBQUFBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAADMwABBoMUFBQUFDsUFBQUFDsUFBQ7FDsUOxQUFDsUOxQUFDsUFBQUFBQUFBQUFDsUFBQUFBQUOxQUFDsUOxQ7FDsUOxQ7FAANBQ=='
      command_off: ''

    'Selector CD':
      friendly_name: "Pioneer Selector CD"
      command_on: 'JgDMAAABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQUFBQUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUOxQ7FAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQUFBQUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUOxQ7FAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQUFBQUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUOxQ7FAANBQ=='
      command_off: ''

    'Selector Tuner':
      friendly_name: "Pioneer Selector Tuner"
      command_on: 'JgDMAAABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FDsUOxQUFBQUFBQ7FBQUFBQUFBQUFBQ7FDsUFBQUFAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FDsUOxQUFBQUFBQ7FBQUFBQUFBQUFBQ7FDsUFBQUFAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FDsUOxQUFBQUFBQ7FBQUFBQUFBQUFBQ7FDsUFBQUFAANBQ=='
      command_off: ''

    'Selector Phono':
      friendly_name: "Pioneer Selector Phono"
      command_on: 'JgDMAAABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FBQUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUFBQ7FAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FBQUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUFBQ7FAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FBQUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUFBQ7FAANBQ=='
      command_off: ''

    'Volume Up':
      friendly_name: "Pioneer Volume Up"
      command_on: 'JgDMAAABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQUFDsUFBQ7FBQUFBQUFBQUOxQ7FDsUOxQ7FDsUOxQUFAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQUFDsUFBQ7FBQUFBQUFBQUOxQ7FDsUOxQ7FDsUOxQUFAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQUFDsUFBQ7FBQUFBQUFBQUOxQ7FDsUOxQ7FDsUOxQUFAANBQ=='
      command_off: ''

    'Selector Tape 1':
      friendly_name: "Pioneer Selector Tape 1"
      command_on: 'JgDMAAABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQUFDsUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUOxQUFAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQUFDsUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUOxQUFAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQUFDsUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUOxQUFAANBQ=='
      command_off: ''

    'Selector Tape 2':
      friendly_name: "Pioneer Selector Tape 2"
      command_on: 'JgDMAAABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUFBQ7FAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUFBQ7FAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FBQUOxQ7FDsUFBQUFBQUFBQ7FBQUOxQ7FDsUFBQ7FAANBQ=='
      command_off: ''

    'Selector Line':
      friendly_name: "Pioneer Selector Line"
      command_on: 'JgDMAAABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FDsUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUFBQUFAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FDsUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUFBQUFAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FDsUOxQ7FBQUFBQ7FBQUFBQ7FDsUOxQUFDsUFBQUFAANBQ=='
      command_off: ''

    'Volume down':
      friendly_name: "Pioneer Volume down"
      command_on: 'JgDMAAABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FDsUFBQ7FBQUFBQUFBQUOxQ7FDsUOxQ7FDsUFBQUFAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FDsUFBQ7FBQUFBQUFBQUOxQ7FDsUOxQ7FDsUFBQUFAADMwABBoMUOxQUFDsUFBQUFDsUFBQ7FBQUOxQUFDsUOxQUFDsUFBQ7FDsUFBQ7FBQUFBQUFBQUOxQ7FDsUOxQ7FDsUFBQUFAANBQ=='
      command_off: ''

