- platform: broadlink      ### RoomName = Rumpus
  host: 192.168.255.255    ## IP Address of the Broadlink
  mac: "78:0f:77:00:xx:xx" ## MAC Address of the Broadlink
  timeout: 15
  type: rm_mini            ## Broadlink type
  switches:
    'Power':
      friendly_name: "TV Power"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOjodHTodHTodHQANBQ=='
      command_off: ''

    'Input 1':
      friendly_name: "TV Input 1"
      command_on: 'JgAYAB0dOh0dHR0dHR0dOjodHR0dHR0dHTodAA0F'
      command_off: ''

    'Input 2':
      friendly_name: "TV Input 2"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOjodHR0dHR06OgANBQ=='
      command_off: ''

    'Input 3':
      friendly_name: "TV Input 3"
      command_on: 'JgAYAB0dOh0dHR0dHR0dOjodHR0dHR06HR0dAA0F'
      command_off: ''

    'Input 4':
      friendly_name: "TV Input 4"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOjodHR0dOjodHQANBQ=='
      command_off: ''

    'Input 5':
      friendly_name: "TV Input 5"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOjodHR0dOjo6HQANBQ=='
      command_off: ''

    'Input 6':
      friendly_name: "TV Input 6"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOjodHR0dOh0dOgANBQ=='
      command_off: ''

    'Input 7':
      friendly_name: "TV Input 7"
      command_on: 'JgAYAB0dOh0dHR0dHR0dOjodHR0dOh0dHR0dAA0F'
      command_off: ''

    'Input 8':
      friendly_name: "TV Input 8"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOjodHTo6HR0dHQANBQ=='
      command_off: ''

    'Input 9':
      friendly_name: "TV Input 9"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOjodHTo6HR06HQANBQ=='
      command_off: ''

    'Memory':
      friendly_name: "TV Memory"
      command_on: 'JgAYAB0dOh0dHR0dHR0dOh0dHR06HR0dHR0dAA0F'
      command_off: ''

    'Input 0':
      friendly_name: "TV Input 0"
      command_on: 'JgAYAB0dOh0dHR0dHR0dOjodHR0dHR0dHR0dAA0F'
      command_off: ''

    'Multiple numbers':
      friendly_name: "TV Multiple numbers"
      command_on: 'JgAUAB0dOh0dHR0dHR0dOjodHTo6OjoADQU='
      command_off: ''

    'Volume down':
      friendly_name: "TV Volume down"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOjo6Oh0dHR06HQANBQ=='
      command_off: ''

    'Volume up':
      friendly_name: "TV Volume up"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOjo6Oh0dHR0dHQANBQ=='
      command_off: ''

    'Channel down':
      friendly_name: "TV Channel down"
      command_on: 'JgAYAB0dOh0dHR0dHR0dOh0dOh0dHR0dHTodAA0F'
      command_off: ''

    'Channel Up':
      friendly_name: "TV Channel Up"
      command_on: 'JgAYAB0dOh0dHR0dHR0dOh0dOh0dHR0dHR0dAA0F'
      command_off: ''

    'Arrow Up':
      friendly_name: "TV Arrow Up"
      command_on: 'JgAUAB0dOh0dHR0dHR0dOjo6Ojo6HR0ADQU='
      command_off: ''

    'Arrow Down':
      friendly_name: "TV Arrow Down"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOjo6Oh0dOh0dHQANBQ=='
      command_off: ''

    'Arrow Left':
      friendly_name: "TV Arrow Left"
      command_on: 'JgAUAB0dOh0dHR0dHR0dOjo6Ojo6Oh0ADQU='
      command_off: ''

    'Arrow Right':
      friendly_name: "TV Arrow Right"
      command_on: 'JgAUAB0dOh0dHR0dHR0dOjo6OjodHToADQU='
      command_off: ''

    'OK':
      friendly_name: "TV OK"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOh0dHR06Ojo6HQANBQ=='
      command_off: ''

    'Red':
      friendly_name: "TV Red"
      command_on: 'JgAYAB0dOh0dHR0dHR0dOh0dHR06Oh0dHR0dAA0F'
      command_off: ''

    'Mute':
      friendly_name: "TV Mute"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOjodHTodHTo6HQANBQ=='
      command_off: ''

    'Green':
      friendly_name: "TV Green"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOh0dHR06Oh0dOgANBQ=='
      command_off: ''

    'AV':
      friendly_name: "TV AV"
      command_on: 'JgAYAB0dOh0dHR0dHR0dOh0dHR0dHTodHR0dAA0F'
      command_off: ''

    'Yellow':
      friendly_name: "TV Yellow"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOh0dHR06HR06OgANBQ=='
      command_off: ''

    'TV':
      friendly_name: "TV TV"
      command_on: 'JgAaAB0dOh0dHR0dHR0dOh0dHR0dHR0dHR0dHR0ADQU='
      command_off: ''

    'Blue':
      friendly_name: "TV Blue"
      command_on: 'JgAWAB0dOh0dHR0dHR0dOh0dHR06OjodHQANBQ=='
      command_off: ''

    'Teletext':
      friendly_name: "TV Teletext"
      command_on: 'JgAYAB0dOh0dHR0dHR0dOh0dHR0dHR0dOh0dAA0F'
      command_off: ''

