- platform: broadlink      ### RoomName = Rumpus
  host: 192.168.255.255    ## IP Address of the Broadlink
  mac: "78:0f:77:00:xx:xx" ## MAC Address of the Broadlink
  timeout: 15
  type: rm_mini            ## Broadlink type
  switches:
    'Power':
      friendly_name: "TV Power"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDg4OKg4qDioOKg4ODg4OKg4ODioOKg4qDioODg4qDgANBQ=='
      command_off: ''

    '3D':
      friendly_name: "TV 3D"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4qDioOKg4ODioOKg4ODioODg4qDioOKg4qDioODg4ODgANBQ=='
      command_off: ''

    'Input TV':
      friendly_name: "TV Input TV"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODioOKg4ODg4ODg4qDg4ODg4qDioODg4qDgANBQ=='
      command_off: ''

    'Input AV':
      friendly_name: "TV Input AV"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDg4OKg4ODg4ODg4ODg4OKg4ODioODg4ODg4ODg4qDgANBQ=='
      command_off: ''

    'Info':
      friendly_name: "TV Info"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4qDioOKg4ODg4OKg4ODg4OKg4qDioODg4qDgANBQ=='
      command_off: ''

    'Exit':
      friendly_name: "TV Exit"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4qDioOKg4qDg4ODg4qDg4OKg4ODgANBQ=='
      command_off: ''

    'Menu':
      friendly_name: "TV Menu"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODioODg4ODioODg4qDg4ODg4qDg4ODg4qDg4OKg4qDgANBQ=='
      command_off: ''

    'Text':
      friendly_name: "TV Text"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODg4ODg4ODg4ODg4qDioODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4qDgANBQ=='
      command_off: ''

    'Subtitles':
      friendly_name: "TV Subtitles"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODg4ODg4ODg4ODg4qDg4OKg4ODg4ODg4ODg4ODg4ODioODg4ODg4ODg4qDgANBQ=='
      command_off: ''

    'Aspect':
      friendly_name: "TV Aspect"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4qDg4ODg4ODg4ODg4ODioOKg4qDioODg4qDioODg4qDg4OKg4qDg4OKg4ODgANBQ=='
      command_off: ''

    'Apps':
      friendly_name: "TV Apps"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4qDioOKg4qDg4ODg4ODioODg4qDioODg4ODg4ODg4ODgANBQ=='
      command_off: ''

    'Home':
      friendly_name: "TV Home"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4qDg4OKg4ODioODg4ODioODg4ODioOKg4qDg4ODg4ODgANBQ=='
      command_off: ''

    'Guide':
      friendly_name: "TV Guide"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4qDioOKg4ODg4ODg4ODioODg4qDioOKg4ODg4ODg4ODgANBQ=='
      command_off: ''

    'Arrow Up':
      friendly_name: "TV Arrow Up"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODioODg4qDg4ODg4qDg4ODg4qDg4OKg4ODg4OKg4qDgANBQ=='
      command_off: ''

    'Arrow Down':
      friendly_name: "TV Arrow Down"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDioODg4qDg4ODg4qDg4OKg4qDg4OKg4ODg4OKg4qDgANBQ=='
      command_off: ''

    'Arrow Left':
      friendly_name: "TV Arrow Left"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODioOKg4qDg4ODg4qDg4ODg4qDioOKg4ODg4OKg4qDgANBQ=='
      command_off: ''

    'Arrow Right':
      friendly_name: "TV Arrow Right"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDioOKg4qDg4ODg4qDg4OKg4qDioOKg4ODg4OKg4qDgANBQ=='
      command_off: ''

    'OK':
      friendly_name: "TV OK"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4qDg4ODg4qDg4OKg4ODg4OKg4ODg4OKg4qDgANBQ=='
      command_off: ''

    'Option':
      friendly_name: "TV Option"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4qDioOKg4ODg4OKg4ODioODg4qDioOKg4ODioODg4ODgANBQ=='
      command_off: ''

    'Back/Return':
      friendly_name: "TV Back/Return"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODioODg4qDioODg4ODioODg4qDg4OKg4ODgANBQ=='
      command_off: ''

    'Red':
      friendly_name: "TV Red"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODioOKg4qDg4ODg4ODg4ODg4qDioOKg4qDgANBQ=='
      command_off: ''

    'Green':
      friendly_name: "TV Green"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODioOKg4qDg4OKg4ODg4ODg4qDioOKg4qDgANBQ=='
      command_off: ''

    'Yellow':
      friendly_name: "TV Yellow"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODioODg4ODioOKg4qDg4ODg4qDg4ODg4qDioOKg4qDgANBQ=='
      command_off: ''

    'Blue':
      friendly_name: "TV Blue"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioOKg4qDg4OKg4qDg4ODg4qDioOKg4qDgANBQ=='
      command_off: ''

    'Volume Up':
      friendly_name: "TV Volume Up"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODioODg4qDgANBQ=='
      command_off: ''

    'Volume Down':
      friendly_name: "TV Volume Down"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4OKg4ODg4OKg4ODg4ODg4ODioODg4qDgANBQ=='
      command_off: ''

    'Channel Up':
      friendly_name: "TV Channel Up"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODioOKg4ODg4ODg4ODioODg4qDioODg4qDgANBQ=='
      command_off: ''

    'Channel Down':
      friendly_name: "TV Channel Down"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDg4OKg4ODioOKg4ODg4OKg4ODioODg4qDioODg4qDgANBQ=='
      command_off: ''

    'Mute':
      friendly_name: "TV Mute"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODioODg4ODioOKg4ODg4ODg4qDg4ODg4qDioODg4qDgANBQ=='
      command_off: ''

    'Input 1':
      friendly_name: "TV Input 1"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODioODg4ODg4ODg4ODg4ODg4qDg4ODg4qDgANBQ=='
      command_off: ''

    'Input 2':
      friendly_name: "TV Input 2"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODioODg4ODg4OKg4ODg4ODg4qDg4ODg4qDgANBQ=='
      command_off: ''

    'Input 3':
      friendly_name: "TV Input 3"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODioODg4ODioODg4ODg4ODg4qDg4ODg4qDg4ODg4qDgANBQ=='
      command_off: ''

    'Input 4':
      friendly_name: "TV Input 4"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4OKg4qDg4ODg4qDg4ODg4qDgANBQ=='
      command_off: ''

    'Input 5':
      friendly_name: "TV Input 5"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODioODg4ODg4ODg4ODioODg4qDg4ODg4qDgANBQ=='
      command_off: ''

    'Input 6':
      friendly_name: "TV Input 6"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDg4OKg4ODioODg4ODg4OKg4ODioODg4qDg4ODg4qDgANBQ=='
      command_off: ''

    'Input 7':
      friendly_name: "TV Input 7"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODioOKg4ODioODg4ODg4ODg4qDioODg4qDg4ODg4qDgANBQ=='
      command_off: ''

    'Input 8':
      friendly_name: "TV Input 8"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDioOKg4ODioODg4ODg4OKg4qDioODg4qDg4ODg4qDgANBQ=='
      command_off: ''

    'Input 9':
      friendly_name: "TV Input 9"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODg4ODg4ODg4OKg4qDg4ODg4qDgANBQ=='
      command_off: ''

    'Input 0':
      friendly_name: "TV Input 0"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4qDioODg4ODg4OKg4ODg4OKg4qDg4ODg4qDgANBQ=='
      command_off: ''

    'Help':
      friendly_name: "TV Help"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4qDg4OKg4ODioODg4ODioOKg4ODioODg4ODgANBQ=='
      command_off: ''

    'Last view':
      friendly_name: "TV Last view"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDg4ODg4ODg4ODg4ODg4ODg4qDioOKg4ODioOKg4ODg4OKg4qDioODg4qDioODg4qDgANBQ=='
      command_off: ''

    'Rewind':
      friendly_name: "TV Rewind"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4ODg4OKg4ODg4ODg4qDioOKg4ODioOKg4ODg4OKg4ODgANBQ=='
      command_off: ''

    'Play':
      friendly_name: "TV Play"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4ODg4ODg4ODg4ODg4qDioOKg4ODg4OKg4ODg4OKg4ODgANBQ=='
      command_off: ''

    'Forward':
      friendly_name: "TV Forward"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4qDioODg4ODg4ODg4qDioODg4qDg4OKg4ODg4OKg4ODgANBQ=='
      command_off: ''

    'Chapter back':
      friendly_name: "TV Chapter back"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4ODg4OKg4qDioODg4qDioOKg4ODioODg4qDg4OKg4ODgANBQ=='
      command_off: ''

    'Pause':
      friendly_name: "TV Pause"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4qDg4ODg4ODg4ODg4qDioODg4ODg4OKg4ODg4OKg4ODgANBQ=='
      command_off: ''

    'Chapter next':
      friendly_name: "TV Chapter next"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4qDg4OKg4qDioODg4qDioODg4ODioODg4qDg4OKg4ODgANBQ=='
      command_off: ''

    'Stop':
      friendly_name: "TV Stop"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4ODioODg4ODg4ODg4qDioOKg4qDg4OKg4ODg4OKg4ODgANBQ=='
      command_off: ''

    'Record':
      friendly_name: "TV Record"
      command_on: 'JgBkAHE5Dg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4ODg4OKg4ODg4ODg4ODg4ODg4ODg4ODg4qDioODg4ODioODg4ODg4ODg4qDg4OKg4ODg4ODg4qDioODg4ODioOKg4ODg4OKg4ODgANBQ=='
      command_off: ''

